import { Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import Transition from "@/components/Transition";

const courierPrime = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "LSNarmadha",
  description: "Generated by create next app",
  icons: {
    icon: "/n.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${courierPrime.variable} antialiased`}>
        <Header />
        <Transition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
