import { Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import Transition from "@/components/Transition";
import Head from "next/head";

const courierPrime = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "LSNarmadha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/lsn.png" />
      </Head>
      <body className={`${courierPrime.variable} antialiased`}>
        <Header />
        <Transition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
